# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fablab Chambéry - Le Prototype
email: contact(at)leprototype.info
description: > # this means to ignore newlines until "baseurl:"
  Ce(tte) œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 3.0 France.
baseurl: "/" # the subpath of your site, e.g. /cms
url: "http://leprototype.info" # the base hostname & protocol for your site
twitter_username: fablabchambery
github_username:  fablab-leprototype

# Build settings
markdown: kramdown
